### ISSUE TITLE
Templated methods in templated class fail to have a definition generated 

### ISSUE THREAD

**Issue by AngelDev06** [Badhi/nvim-treesitter-cpp-tools#40] opened 2024-08-18 09:22 UTC
Say I have this class

```
template <typename T>
class A
{
public:
  template <typename T2>
  A(T2&& arg); 
};
```

An attempt to provide a definition for the templated constructor gives the following error:

```
E5108: Error executing lua .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:133: attempt to index local 'type_identifier' (a nil value)
```

With the following traceback:
```
stack traceback:
      .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:133: in function 'check_get_template_info'     
      .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:154: in function 'get_member_function_data'
      .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:268: in function 'runner'
      .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:40: in function 'run_on_nodes'
      .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:278: in function 'run'
      [string ":lua"]:1: in main chunk
```

**Comment by Badhi** [comment] 2024-09-28 21:59
hmm weird, I cant recreate the issue. It works for me

![image](https://github.com/user-attachments/assets/2ce76d48-f204-4fb5-b985-38177918b61b)

**Comment by Badhi** [comment] 2024-10-16 05:08
Closing since the issue cannot be reproduced. Feel free to open if the issue exists

**Closed by Badhi** 2024-10-16 05:08 UTC
